name: shynder
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <=3.10.5"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.5
  location: 5.0.0
  grpc: 3.2.2
  protobuf: 3.0.0
  json_theme: 6.0.2+3
  file_picker: 5.3.2
  google_maps_flutter: 2.3.1
  auto_size_text: 3.0.0
  url_launcher: 6.1.12
  flutter_dotenv: 5.1.0
  dio: 5.3.2
  shared_preferences: 2.2.0
  fluttertoast: 8.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  protoc_plugin: 21.0.2

flutter:
  assets:
    - assets/logo.png
    - assets/theme.json
    - .env
  uses-material-design: true
